Repository lmcrean/dottie, pull requests merged in 2025-04, with the labels that each got.

#181 svg graphics added to assessment pages
  frontend/public/assessmentAssets/age.svg
  frontend/public/assessmentAssets/cycle.svg
  frontend/public/assessmentAssets/duration.svg
  frontend/public/assessmentAssets/flow.svg
  frontend/public/assessmentAssets/othersymptoms.svg
  frontend/public/assessmentAssets/pain.svg
  frontend/src/pages/assessment/age-verification/page.tsx
  frontend/src/pages/assessment/cycle-length/page.tsx
  frontend/src/pages/assessment/flow/page.tsx
  frontend/src/pages/assessment/pain/page.tsx
  frontend/src/pages/assessment/period-duration/page.tsx
  frontend/src/pages/assessment/symptoms/page.tsx
Labels: Feat: Assessment, Action required: pull from main, Action required: confirm `npm run build`

#262 Styling (landing page): "Menstrual Health" fades from black to pink after 3 seconds
  frontend/src/globals.css
  frontend/src/pages/auth/sign-in.tsx
Labels: Action required: add screenshots, Action required: confirm `npm run build`

#255 feat/fix: Unify color scheme and improve password validation
  backend/README.md
  backend/dev.sqlite3
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ui/!to-migrate/button.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/lib/validations/auth.ts
  frontend/src/pages/auth/forgot-password.tsx
  frontend/src/pages/auth/reset-password.tsx
  frontend/src/pages/auth/sign-in.tsx
  frontend/src/pages/auth/sign-up.tsx
  frontend/src/pages/user/account-form.tsx
  frontend/src/pages/user/password-form.tsx
  frontend/tailwind.config.ts
Labels: Action required - pull from main, Action required: confirm `npm run build`

#286 Styling (landing page): "Menstrual Health" fades from black to pink after 3 seconds
  frontend/src/pages/landing-page/page.tsx
Labels: Action required: add screenshots

#289 Feature request: Dark mode toggle #288
  frontend/public/logo-mascot.png
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/AuthLayout.tsx
  frontend/src/components/ThemeToggle.tsx
  frontend/src/components/navigation/Header.tsx
  frontend/src/components/ui/!to-migrate/button.tsx
  frontend/src/components/ui/!to-migrate/form-input.tsx
  frontend/src/components/ui/!to-migrate/input-otp.tsx
  frontend/src/components/ui/!to-migrate/input.tsx
  frontend/src/components/ui/!to-migrate/select.tsx
  frontend/src/components/ui/!to-migrate/textarea.tsx
  frontend/src/components/ui/!to-migrate/toggle.tsx
  frontend/src/components/ui/PasswordInput.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/context/ThemeContext.tsx
  frontend/src/globals.css
  frontend/src/main.tsx
  frontend/src/pages/assessment/age-verification/page.tsx
  frontend/src/pages/assessment/cycle-length/page.tsx
  frontend/src/pages/assessment/flow/page.tsx
  frontend/src/pages/assessment/history/[id]/page.tsx
  frontend/src/pages/assessment/history/page.tsx
  frontend/src/pages/assessment/pain/page.tsx
  frontend/src/pages/assessment/period-duration/page.tsx
  frontend/src/pages/assessment/resources/page.tsx
  frontend/src/pages/assessment/results/page.tsx
  frontend/src/pages/assessment/symptoms/page.tsx
  frontend/src/pages/auth/sign-in.tsx
  frontend/src/pages/auth/sign-up.tsx
  frontend/src/pages/landing-page/page.tsx
  frontend/src/pages/user/account-form.tsx
  frontend/src/pages/user/account-layout.tsx
  frontend/src/pages/user/account-sidebar.tsx
Labels: nice to have, tailwindcss, Rendering
